//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTutorWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eTutorEntities1 : DbContext
    {
        public eTutorEntities1()
            : base("name=eTutorEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<etutor_organization> etutor_organization { get; set; }
        public virtual DbSet<message> messages { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<password> passwords { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<subscription> subscriptions { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<tutoring_sessions> tutoring_sessions { get; set; }
        public virtual DbSet<tutor> tutors { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
