//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTutorWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class etutor_organization
    {
        public int e_tutor_daily_id { get; set; }
        public string date_time { get; set; }
        public float total { get; set; }
    }
}
