//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTutorWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int transactions_id { get; set; }
        public string date { get; set; }
        public int student_id { get; set; }
        public int tutor_id { get; set; }
        public int course_id { get; set; }
        public int tutoring_session_id { get; set; }
        public float transaction_amount { get; set; }
        public Nullable<float> e_tutor_provision_percent { get; set; }
        public string status { get; set; }
    }
}
